"""Add GPU models

Revision ID: 4516c726c22d
Revises: 4b12ccee5729
Create Date: 2024-01-03 22:16:12.497208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4516c726c22d'
down_revision = '4b12ccee5729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpu_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('gpu_type', sa.String(length=80), nullable=False),
    sa.Column('gpu_memory', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('gpu_booking',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gpu_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpu_instance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('gpu_usage',
    sa.Column('usage_id', sa.Integer(), nullable=False),
    sa.Column('gpu_id', sa.Integer(), nullable=False),
    sa.Column('usage_duration', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpu_instance.id'], ),
    sa.PrimaryKeyConstraint('usage_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gpu_usage')
    op.drop_table('gpu_booking')
    op.drop_table('gpu_instance')
    # ### end Alembic commands ###
