"""Initial migration

Revision ID: 7dd230729c78
Revises: 
Create Date: 2024-01-04 16:24:17.204262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd230729c78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpu_instance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('gpu_type', sa.String(length=80), nullable=False),
    sa.Column('gpu_memory', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'IN_USE', 'BOOKED', 'MAINTENANCE', name='gpu_status'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('gpu_booking',
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('gpu_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpu_instance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('gpu_usage',
    sa.Column('usage_id', sa.Integer(), nullable=False),
    sa.Column('gpu_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('usage_duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['gpu_booking.booking_id'], ),
    sa.ForeignKeyConstraint(['gpu_id'], ['gpu_instance.id'], ),
    sa.PrimaryKeyConstraint('usage_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gpu_usage')
    op.drop_table('gpu_booking')
    op.drop_table('user')
    op.drop_table('gpu_instance')
    # ### end Alembic commands ###
