"""Added queue models

Revision ID: bf4411718ca3
Revises: d8c7aab50993
Create Date: 2024-01-04 23:41:25.681552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf4411718ca3'
down_revision = 'd8c7aab50993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpu_queue_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ALLOCATED', 'CANCELLED', name='gpu_queue_status'), nullable=False),
    sa.Column('queue_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gpu_queue_entry')
    # ### end Alembic commands ###
