"""Added GPU usage and booking relationship

Revision ID: cf277ee5b5f8
Revises: 4516c726c22d
Create Date: 2024-01-04 00:13:40.403191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf277ee5b5f8'
down_revision = '4516c726c22d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpu_usage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'gpu_booking', ['booking_id'], ['booking_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpu_usage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('booking_id')

    # ### end Alembic commands ###
