"""added metrics attributes

Revision ID: d8c7aab50993
Revises: 7dd230729c78
Create Date: 2024-01-04 18:23:59.283512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8c7aab50993'
down_revision = '7dd230729c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpu_instance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utilization_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('peak_memory_usage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('average_load', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('error_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('energy_consumption', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_temperature', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('network_usage', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gpu_instance', schema=None) as batch_op:
        batch_op.drop_column('network_usage')
        batch_op.drop_column('max_temperature')
        batch_op.drop_column('energy_consumption')
        batch_op.drop_column('error_count')
        batch_op.drop_column('average_load')
        batch_op.drop_column('peak_memory_usage')
        batch_op.drop_column('utilization_percentage')

    # ### end Alembic commands ###
